name=input("enter your name:")
print(name)
age=int(input("enter your age:"))
print(age)
dob=input("enter your dob:")
print(dob)
height=input("enter your height:")
print(height)
weight=input("enter your weight:")
print(weight)
degree=input("enter your degree:")
print(degree)
gender=input("enter your gender:")
print(gender)

print(name,"is alive")